@host = localhost
@port = 80
@origin = {{host}}:{{port}}

### Authentication - Register
# @name register
POST http://{{origin}}/api/auth/register
Content-Type: application/json

{
  "email": "john.doe@example.com",
  "password": "example123",
  "name": {
    "first": "John",
    "last": "Doe"
  },
  "picture": null
}

### Authentication - Login
# @name login
POST http://{{origin}}/api/auth/login
Content-Type: application/json

{
  "email": "john.doe@example.com",
  "password": "example123"
}

### Authentication - Update Details
@accessToken = {{login.response.body.accessToken}}

PATCH http://{{origin}}/api/auth/user
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "name": {
    "first": "Johnathan",
    "last": "Doe"
  }
}

### Authentication - Delete Account
DELETE http://{{origin}}/api/auth/user
Authorization: Bearer {{accessToken}}